version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3309:3306" # Mapeando porta 3309 do host para porta 3306 do container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agencia_de_viagens_swing
    volumes:
      - ./init:/docker-entrypoint-initdb.d